edge_type: surface
fit_type: fancy
interpolation_method: linear
n_points: 256
n_smoothing_iterations: 15
n_tracing_iterations: 1
outlier_tolerance: 1.5
remove_outliers: true
resampling_length: 5.0
sampling_distance: 1.0
smoothing_sigma: 1.0
target_voxelsize: 0.2868
trace_length: 30.0
return_intermediate_results: true
voxelsize: !!ndarray
- 0.47
- 0.1036
- 0.1036
