edge_type: interior
fit_type: fancy
interpolation_method: linear
n_points: 256
n_smoothing_iterations: 15
n_tracing_iterations: 2
outlier_tolerance: 1.5
remove_outliers: true
resampling_length: 10.0
sampling_distance: 2.0
smoothing_sigma: 2.0
target_voxelsize: 0.23
trace_length: 80.0
voxelsize_z: 0.37
voxelsize_y: 0.0901
voxelsize_x: 0.0901
